### ISSUE TITLE
preprocessors not firing...

### ISSUE THREAD

**Issue by z3cka** [UCLALibrary/ucla_gateway#7]
this is due to a `}` in the wrong place and all the preprocessors are nested in [ucla_gateway_preprocess_page](https://github.com/UCLALibrary/ucla_gateway/blob/62a74853863baf750d442c4dd1448f0c29ae2191/ucla_gateway.theme#L39). Fix coming.

**Comment by emb03** [comment]
@z3cka good catch, do you want me to pull this into my local?
